# Generated by Django 6.1.1 on 2026-09-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(choices=[('30ML', '30 ml'), ('50ML', '50 ml'), ('100ML', '100 ml'), ('SHADE-L', 'Light'), ('SHADE-M', 'Medium'), ('SHADE-D', 'Deep'), ('ONE', 'One Size')], max_length=10),
        ),
    ]
